# Generated by Django 5.0.2 on 2024-02-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ggrid', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='price',
            field=models.FloatField(default=1.99),
        ),
    ]
