# Generated by Django 5.0.2 on 2024-02-16 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ggrid', '0006_alter_category_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
