# Generated by Django 5.0.2 on 2024-02-16 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ggrid', '0007_alter_category_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='picture',
        ),
    ]
