# Generated by Django 5.0.2 on 2024-02-23 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ggrid', '0008_remove_category_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ggrid.shelf')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ggrid.category')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ggrid.recipe')),
            ],
        ),
    ]
