# Generated by Django 5.0.2 on 2024-02-26 23:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ggrid', '0009_recipe_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keystroke',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keystroke',
            name='key',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
